/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataQualityIndexRouteImport } from './routes/data-quality.index'
import { Route as DataGenerationIndexRouteImport } from './routes/data-generation.index'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityIndexRoute = DataQualityIndexRouteImport.update({
  id: '/data-quality/',
  path: '/data-quality/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGenerationIndexRoute = DataGenerationIndexRouteImport.update({
  id: '/data-generation/',
  path: '/data-generation/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/data-generation/': typeof DataGenerationIndexRoute
  '/data-quality/': typeof DataQualityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/data-generation': typeof DataGenerationIndexRoute
  '/data-quality': typeof DataQualityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/data-generation/': typeof DataGenerationIndexRoute
  '/data-quality/': typeof DataQualityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/data-generation/' | '/data-quality/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/data-generation' | '/data-quality'
  id: '__root__' | '/' | '/contact' | '/data-generation/' | '/data-quality/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DataGenerationIndexRoute: typeof DataGenerationIndexRoute
  DataQualityIndexRoute: typeof DataQualityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality/': {
      id: '/data-quality/'
      path: '/data-quality'
      fullPath: '/data-quality/'
      preLoaderRoute: typeof DataQualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-generation/': {
      id: '/data-generation/'
      path: '/data-generation'
      fullPath: '/data-generation/'
      preLoaderRoute: typeof DataGenerationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DataGenerationIndexRoute: DataGenerationIndexRoute,
  DataQualityIndexRoute: DataQualityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
